[build]
  command = "npm run build"
  functions = ".netlify/functions"
  publish = "build"

[dev]
  command = "npm start"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/progress"
  status = 200
